<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260828090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Self-hosted call booking: slot columns on inquiry, availability rules, settings';
    }

    public function up(Schema $schema): void
    {
        // WITHOUT TIME ZONE is deliberate: all times are naive Europe/Berlin
        // wall-clock values (single-timezone business, see SlotFinder). A 09:00
        // slot stays 09:00 on the wall clock across DST switches.
        $this->addSql('ALTER TABLE inquiry ADD starts_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE inquiry ADD call_type VARCHAR(10) DEFAULT NULL');
        $this->addSql("ALTER TABLE inquiry ADD status VARCHAR(20) DEFAULT 'confirmed' NOT NULL");
        // Double booking is impossible at the DB level; cancelled rows free the slot.
        $this->addSql("CREATE UNIQUE INDEX uniq_inquiry_slot ON inquiry (starts_at) WHERE (status = 'confirmed')");

        $this->addSql('CREATE TABLE availability_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, weekday SMALLINT NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE setting (name VARCHAR(50) NOT NULL, value TEXT NOT NULL, PRIMARY KEY (name))');

        // Seed defaults — editable from the admin panel (branch 2), until then via SQL.
        foreach ([1, 2, 3, 4, 5] as $weekday) {
            $this->addSql("INSERT INTO availability_rule (weekday, start_time, end_time) VALUES ($weekday, '09:00', '17:00')");
        }
        $this->addSql("INSERT INTO setting (name, value) VALUES ('meet_link', 'https://meet.google.com/jre-kcoc-swk')");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE availability_rule');
        $this->addSql('DROP TABLE setting');
        $this->addSql('DROP INDEX uniq_inquiry_slot');
        $this->addSql('ALTER TABLE inquiry DROP starts_at');
        $this->addSql('ALTER TABLE inquiry DROP call_type');
        $this->addSql('ALTER TABLE inquiry DROP status');
    }
}
